(function(g){var window=this;var iBa=function(a,b){return g.Vb(a,b)},n6=function(a){g.Om(a,"zx",g.xb());
return a},o6=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Rm(a.g,b,c)},jBa=function(a,b){var c=[];
g.uk(b,function(a){try{var b=g.kD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.jD(b)&&c.push(a):c.push(a)},a);
return c},kBa=function(a,b){var c=jBa(a,b);
(0,g.B)(c,function(a){g.kD.prototype.remove.call(this,a)},a)},lBa=function(a,b,c,d){var e=new g.Fm(null,void 0);
a&&g.Gm(e,a);b&&g.Hm(e,b);c&&g.Im(e,c);d&&g.Jm(e,d);return e},mBa=function(a){g.gG[a]&&(a=g.gG[a],(0,g.B)(a,function(a){g.eG[a]&&delete g.eG[a]}),a.length=0)},nBa=function(a){var b=g.dG();
if(b)if(b.clear(a),a)mBa(a);else for(var c in g.gG)mBa(c)},p6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.zm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",oBa(this,a.capabilities||""),pBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},oBa=function(a,b){a.capabilities.clear();
(0,g.Ld)(b.split(","),g.Ea(iBa,qBa)).forEach(function(b){a.capabilities.add(b)})},pBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},q6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},r6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},rBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},sBa=function(a){return new q6(a)},tBa=function(a){return g.ya(a)?(0,g.G)(a,sBa):[]},s6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},t6=function(a){return g.ya(a)?"["+(0,g.G)(a,s6).join(",")+"]":"null"},u6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},uBa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},v6=function(a,b){return g.Ma(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},w6=function(a,b){return g.Ma(a,function(a){return r6(a,b)})},vBa=function(){var a=(0,g.$G)();
a&&kBa(a,a.g.Jd(!0))},x6=function(){var a=g.cH("yt-remote-connected-devices")||[];
g.ib(a);return a},wBa=function(a){if(g.Ra(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},xBa=function(a){g.bH("yt-remote-connected-devices",a,86400)},z6=function(){if(y6)return y6;
var a=g.cH("yt-remote-device-id");a||(a=u6(),g.bH("yt-remote-device-id",a,31536E3));for(var b=x6(),c=1,d=a;g.Qa(b,d);)c++,d=a+"#"+c;return y6=d},A6=function(){var a=x6(),b=z6();
g.Qa(a,b);g.eH()&&g.kb(a,b);a=wBa(a);if(g.Ra(a))try{g.NG("remote_sid")}catch(c){}else try{g.MG("remote_sid",a.join(","),-1)}catch(c){}},yBa=function(){return g.cH("yt-remote-session-browser-channel")},zBa=function(){return g.cH("yt-remote-local-screens")||[]},ABa=function(){g.bH("yt-remote-lounge-token-expiration",!0,86400)},BBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(zBa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.om)(c,function(a){return!g.Qa(b,a)})&&ABa();
g.bH("yt-remote-local-screens",a,31536E3)},CBa=function(a,b){g.bH("yt-remote-session-browser-channel",a);
g.bH("yt-remote-session-screen-id",b);var c=x6(),d=z6();g.Qa(c,d)||c.push(d);xBa(c);A6()},B6=function(a){a||(g.dH("yt-remote-session-screen-id"),g.dH("yt-remote-session-video-id"));
A6();a=x6();g.Va(a,z6());xBa(a)},DBa=function(){if(!C6){var a=g.vD();
a&&(C6=new g.eD(a))}return C6?!!C6.get("yt-remote-use-staging-server"):!1},EBa=function(){var a=window.document.createElement("a");
g.Zc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},FBa=function(a,b){var c=g.Ed("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.ad(c,g.de("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},GBa=function(){var a=EBa(),b=window.document.getElementById(a),c=b&&g.pF(b,"loaded");
c||b&&!c||(b=FBa(a,function(){g.pF(b,"loaded")||(g.oF(b,"loaded","true"),g.kG(a),g.dE(g.Ea(nBa,a),0))}))},D6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},HBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},E6=function(a){a.length?IBa(a.shift(),function(){E6(a)}):F6()},JBa=function(a){return"chrome-extension://"+a+G6},IBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},H6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},F6=function(){var a=HBa();
a&&a(!1,"No cast extension found")},I6=function(){if(KBa){var a=2,b=HBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;IBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",F6,c)}},LBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(I6(),a({command:"cast.sender.init"}))},MBa=function(){I6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);E6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+G6,"//www.gstatic.com/eureka/clank"+G6])},J6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.Yc=b;this.B=(0,g.z)(this.oI,this);this.g=!1;this.l=0;this.o=this.va=null;this.A=[]},K6=function(){},L6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Vm(this);this.l=new g.ug;this.l.setInterval(250)},OBa=function(a,b,c){a.oj=1;
a.Ug=n6(b.clone());a.yi=c;a.C=!0;NBa(a,null)},M6=function(a,b,c,d,e){a.oj=1;
a.Ug=n6(b.clone());a.yi=null;a.C=c;e&&(a.GC=!1);NBa(a,d)},NBa=function(a,b){a.Tj=(0,g.F)();
N6(a);a.sh=a.Ug.clone();o6(a.sh,"t",a.D);a.Rl=0;a.Nc=a.g.Aq(a.g.Ll()?b:null);0<a.gr&&(a.Go=new g.Zk((0,g.z)(a.UD,a,a.Nc),a.gr));a.A.T(a.Nc,"readystatechange",a.CT);var c=a.Wh?g.cc(a.Wh):{};a.yi?(a.vp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nc.send(a.sh,a.vp,a.yi,c)):(a.vp="GET",a.GC&&!g.Ad&&(c.Connection="close"),a.Nc.send(a.sh,a.vp,null,c));a.g.jf(1)},RBa=function(a,b,c){for(var d=!0;!a.Ih&&a.Rl<c.length;){var e=PBa(a,c);
if(e==O6){4==b&&(a.Vg=4,P6(15),d=!1);break}else if(e==QBa){a.Vg=4;P6(16);d=!1;break}else Q6(a,e)}4==b&&0==c.length&&(a.Vg=1,P6(17),d=!1);a.qf=a.qf&&d;d||(R6(a),S6(a))},PBa=function(a,b){var c=a.Rl,d=b.indexOf("\n",c);
if(-1==d)return O6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return QBa;d+=1;if(d+c>b.length)return O6;var e=b.substr(d,c);a.Rl=d+c;return e},TBa=function(a,b){a.Tj=(0,g.F)();
N6(a);var c=b?window.location.hostname:"";a.sh=a.Ug.clone();g.Om(a.sh,"DOMAIN",c);g.Om(a.sh,"t",a.D);try{a.rf=new window.ActiveXObject("htmlfile")}catch(n){R6(a);a.Vg=7;P6(22);S6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in T6)k=T6[l];else if(l in SBa)k=T6[l]=SBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=T6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.bd(g.wc("b/12014412"),d);a.rf.open();a.rf.write(g.Tc(c));a.rf.close();a.rf.parentWindow.m=(0,g.z)(a.IS,a);a.rf.parentWindow.d=(0,g.z)(a.TB,a,!0);a.rf.parentWindow.rpcClose=(0,g.z)(a.TB,a,!1);c=a.rf.createElement("DIV");a.rf.parentWindow.document.body.appendChild(c);d=g.Jc(a.sh.toString());d=g.rb(g.Gc(d));d=g.bd(g.wc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Tc(d);
a.g.jf(1)},N6=function(a){a.Nu=(0,g.F)()+a.B;
UBa(a,a.B)},UBa=function(a,b){if(null!=a.lk)throw Error("WatchDog timer not null");
a.lk=U6((0,g.z)(a.ZS,a),b)},V6=function(a){a.lk&&(g.w.clearTimeout(a.lk),a.lk=null)},S6=function(a){a.g.Wx()||a.Ih||a.g.uo(a)},R6=function(a){V6(a);
g.cf(a.Go);a.Go=null;a.l.stop();g.an(a.A);if(a.Nc){var b=a.Nc;a.Nc=null;b.abort();b.dispose()}a.rf&&(a.rf=null)},Q6=function(a,b){try{a.g.MB(a,b),a.g.jf(4)}catch(c){}},WBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;VBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){WBa(a,b,c,d,f)},f)})}},VBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{W6(d),c(!0)}catch(e){}};
d.onerror=function(){try{W6(d),c(!1)}catch(e){}};
d.onabort=function(){try{W6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{W6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},W6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},XBa=function(a){this.g=a;
this.l=new K6},YBa=function(a){var b=X6(a.g,a.rk,"/mail/images/cleardot.gif");
n6(b);WBa(b.toString(),5E3,(0,g.z)(a.AH,a),3,2E3);a.jf(1)},Z6=function(a){var b=a.g.G;
if(null!=b)P6(5),b?(P6(11),Y6(a.g,a,!1)):(P6(12),Y6(a.g,a,!0));else if(a.ne=new L6(a,void 0,void 0,void 0),a.ne.Wh=a.ar,b=a.g,b=X6(b,b.Ll()?a.Pk:null,a.fr),P6(5),!g.yd||g.sc(10))o6(b,"TYPE","xmlhttp"),M6(a.ne,b,!1,a.Pk,!1);else{o6(b,"TYPE","html");var c=a.ne;a=!!a.Pk;c.oj=3;c.Ug=n6(b.clone());TBa(c,a)}},$6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new K6;this.F=a||null;this.G=null!=b?b:null;this.C=c||!1},ZBa=function(a,b){this.g=a;
this.map=b;this.context=null},$Ba=function(a){g.ef.call(this,"statevent",a)},aCa=function(a,b){g.ef.call(this,"timingevent",a);
this.size=b},bCa=function(a){g.ef.call(this,"serverreachability",a)},eCa=function(a){cCa(a);
if(3==a.g){var b=a.xl++,c=a.qn.clone();g.Om(c,"SID",a.o);g.Om(c,"RID",b);g.Om(c,"TYPE","terminate");a7(a,c);b=new L6(a,a.o,b,void 0);b.oj=2;b.Ug=n6(c.clone());(new window.Image).src=b.Ug;b.Tj=(0,g.F)();N6(b)}dCa(a)},fCa=function(a){a.VH(1,0);
a.qn=X6(a,null,a.Zq);b7(a)},cCa=function(a){a.Lg&&(a.Lg.abort(),a.Lg=null);
a.qc&&(a.qc.cancel(),a.qc=null);a.hg&&(g.w.clearTimeout(a.hg),a.hg=null);c7(a);a.Od&&(a.Od.cancel(),a.Od=null);a.Ng&&(g.w.clearTimeout(a.Ng),a.Ng=null)},gCa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new ZBa(a.yO++,b));2!=a.g&&3!=a.g||b7(a)},b7=function(a){a.Od||a.Ng||(a.Ng=U6((0,g.z)(a.RB,a),0),a.cj=0)},iCa=function(a,b){if(1==a.g){if(!b){a.xl=Math.floor(1E5*Math.random());
var c=a.xl++,d=new L6(a,"",c,void 0);d.Wh=null;var e=d7(a),f=a.qn.clone();g.Om(f,"RID",c);g.Om(f,"CVER","1");a7(a,f);OBa(d,f,e);a.Od=d;a.g=2}}else 3==a.g&&(b?hCa(a,b):0==a.l.length||a.Od||hCa(a))},hCa=function(a,b){if(b)if(6<a.Kh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.xl-1;var d=d7(a)}else c=b.F,d=b.yi;else c=a.xl++,d=d7(a);var e=a.qn.clone();g.Om(e,"SID",a.o);g.Om(e,"RID",c);g.Om(e,"AID",a.Bj);a7(a,e);c=new L6(a,a.o,c,a.cj+1);c.Wh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Od=c;OBa(c,e,d)},a7=function(a,b){if(a.md){var c=a.md.Ex();
c&&g.Kb(c,function(a,c){g.Om(b,c,a)})}},d7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Kh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Kh?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},jCa=function(a){a.qc||a.hg||(a.D=1,a.hg=U6((0,g.z)(a.QB,a),0),a.Qi=0)},e7=function(a){if(a.qc||a.hg||3<=a.Qi)return!1;
a.D++;a.hg=U6((0,g.z)(a.QB,a),kCa(a,a.Qi));a.Qi++;return!0},Y6=function(a,b,c){a.tp=c;
a.Ef=b.og;a.C||fCa(a)},c7=function(a){null!=a.Mh&&(g.w.clearTimeout(a.Mh),a.Mh=null)},kCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},f7=function(a,b){if(2==b||9==b){var c=null;
a.md&&(c=null);var d=(0,g.z)(a.xU,a);c||(c=new g.Fm("//www.google.com/images/cleardot.gif"),n6(c));VBa(c.toString(),1E4,d)}else P6(2);lCa(a,b)},lCa=function(a,b){a.g=0;
a.md&&a.md.zw(b);dCa(a);cCa(a)},dCa=function(a){a.g=0;
a.Ef=-1;if(a.md)if(0==a.A.length&&0==a.l.length)a.md.mq();else{g.Ya(a.A);var b=g.Ya(a.l);a.A.length=0;a.l.length=0;a.md.mq(b)}},X6=function(a,b,c){var d=g.Pm(c);
if(""!=d.l)b&&g.Hm(d,b+"."+d.l),g.Im(d,d.B);else{var e=window.location;d=lBa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Ck&&g.Kb(a.Ck,function(a,b){g.Om(d,b,a)});
g.Om(d,"VER",a.Kh);a7(a,d);return d},U6=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},P6=function(a){g7.dispatchEvent(new $Ba(g7,a))},mCa=function(){},nCa=function(a,b){this.action=a;
this.params=b||{}},h7=function(a,b){g.K.call(this);
this.g=new g.gu(this.zS,0,this);g.L(this,this.g);this.Yc=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},i7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.dD;this.l=new h7(this.gV,this);this.g=this.Ua=null;this.I=!1;this.B=null;this.G="";this.F=this.A=0;this.D=[];this.L=c||!1},oCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.tp,sessionId:a.g.o,arrayId:a.g.Bj}},pCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&iCa(a.g),eCa(a.g));a.F=0},j7=function(a){return!!a.g&&3==a.g.g},qCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},k7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Lg(a)||"";b&&(this.port=":"+b);this.domain=g.Kg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},l7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Ug(c+b,{})},m7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),rd:g.Ea(a.B,e)};c&&(a.Jb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.BE(b,a)},uCa=function(){var a=rCa;
sCa();n7.push(a);tCa(n7)},o7=function(a,b){sCa();
var c=n7,d=vCa(a,String(b));g.Ra(c)?wCa(d):(tCa(c),(0,g.B)(c,function(a){a(d)}))},sCa=function(){n7||(n7=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",n7,void 0))},wCa=function(a){var b=(p7+1)%50;
p7=b;q7[b]=a;r7||(r7=49==b)},tCa=function(a){var b=q7;
if(b[0]){var c=p7,d=r7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
q7=Array(50);p7=-1;r7=!1}},vCa=function(a,b){var c=((0,g.F)()-xCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},s7=function(a){g.WF.call(this);
this.D=a;this.g=[]},yCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},zCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Ld)(a.g,function(a){return!!v6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=yCa(a,b[d])||c;return c},ACa=function(a,b){var c=a.g.length;
a.g=(0,g.Ld)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},t7=function(a,b,c,d){g.WF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.va=window.NaN},v7=function(a){s7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;u7(this);this.info("Initializing with "+t6(this.g))},BCa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=l7(a.o,"/pairing/get_lounge_token_batch");
m7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.BI,a),(0,g.z)(a.AI,a))}},u7=function(a){var b=tBa(zBa());
b=(0,g.Ld)(b,function(a){return!a.uuid});
return zCa(a,b)},w7=function(a,b){BBa((0,g.G)(a.g,rBa));
b&&ABa()},y7=function(a,b){g.WF.call(this);
this.C=b;var c=g.cH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Qa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;x7("Initialized with "+g.Bg(this.g))},CCa=function(a,b,c){var d=l7(a.B,"/pairing/get_screen_availability");
m7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},z7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(x7("Updated online screens: "+g.Bg(a.g)),a.g=b,a.P("screenChange"));DCa(a)},A7=function(a){(0,window.isNaN)(a.o)||g.fE(a.o);
a.o=g.dE((0,g.z)(a.cu,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},x7=function(a){o7("OnlineScreenService",a)},ECa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.ac("Requesting availability of screen w/o lounge token.")});
return b},DCa=function(a){a=g.Sb(g.Lb(a.g,function(a){return a}));
g.ib(a);a.length?g.bH("yt-remote-online-screen-ids",a.join(","),60):g.dH("yt-remote-online-screen-ids")},B7=function(a){s7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};FCa(this)},HCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ge();if(k=(c?w6(k,c):null)||w6(k,b)){k.uuid=b;var l=C7(a,k);CCa(a.l,l,function(a){e(a?l:null)})}else c?GCa(a,c,(0,g.z)(function(a){var f=C7(this,new q6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));CCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},ICa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},GCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Jb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.BE(l7(a.C,"/pairing/get_lounge_token_batch"),e)},JCa=function(a){a.g=a.o.ge();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+t6(a.g))},FCa=function(a){D7(a);
a.o=new v7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.RI,a));JCa(a);a.A=tBa(g.cH("yt-remote-automatic-screen-cache")||[]);D7(a);a.info("Initializing automatic screens: "+t6(a.A));a.l=new y7(a.C,(0,g.z)(a.ge,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},C7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=w6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.bH("yt-remote-automatic-screen-cache",(0,g.G)(a.A,rBa)));D7(a);a.B[b.uuid]=b.id;g.bH("yt-remote-device-id-map",a.B,31536E3);return b},D7=function(a){a.B=g.cH("yt-remote-device-id-map")||{}},E7=function(a,b,c){g.WF.call(this);
this.L=c;this.G=a;this.l=b;this.o=null},F7=function(a,b){o7(a.L,b)},G7=function(a,b){E7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.mV,this);this.B=(0,g.z)(this.lT,this);this.A=g.dE((0,g.z)(function(){KCa(this,null)},this),12E4)},LCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Bg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){F7(this,"Failed to send message: getMdxSessionStatus.")},a)):F7(a,"Sending yt message without session: "+g.Bg(b))},KCa=function(a,b){g.fE(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.vo,a),d=(0,g.z)(a.ke,a);a.Px(b,c,d,5)}}else a.ke(Error("Waiting for session status timed out."))},H7=function(a,b,c){E7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.pV,this);this.g=g.y},MCa=function(a){a.g=a.G.bE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.vo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.ke(a)},a))},NCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}DBa()&&(b.env_useStageMdx=1);return g.Sg(b)},I7=function(a,b){E7.call(this,a,b,"ManualSession");
this.g=g.dE((0,g.z)(this.Cj,this,null),150)},J7=function(a,b,c,d){g.WF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.NR,this)},OCa=function(a,b){return b?g.Ma(a.o,function(a){return r6(b,a.label)},a):null},K7=function(a){o7("Controller",a)},rCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},L7=function(a){return a.B||!!a.o.length||!!a.g},M7=function(a,b,c){b!=a.g&&(g.cf(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.OB,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Cj(null)):a.P("yt-remote-cast2-session-change",null))},PCa=function(a){var b=a.l.aE(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&r6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=OCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},VCa=function(a,b,c,d,e,f,k){QCa()?RCa(b,e,f,k)&&(O7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?SCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?SCa(a,c):(P7("Failed to load cast API: "+d),Q7(!1),O7(!1),g.dH("yt-remote-cast-available"),g.dH("yt-remote-cast-receiver"),TCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):GBa():H6("CriOS")?LBa():H6("Android")&&H6("Chrome/")&&window.navigator.presentation?MBa():window.chrome&&window.navigator.presentation&&!H6("Edge")?(I6(),E6(UCa.map(JBa))):F6())):N7("Cannot initialize because not running Chrome")},TCa=function(){N7("dispose");
var a=R7();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);WCa(!1);g.iG(S7);S7.length=0},T7=function(){return!!g.cH("yt-remote-cast-installed")},XCa=function(){var a=g.cH("yt-remote-cast-receiver");
return a?a.friendlyName:null},YCa=function(){N7("clearCurrentReceiver");
g.dH("yt-remote-cast-receiver")},ZCa=function(){return T7()?R7()?R7().getCastSession():(P7("getCastSelector: Cast is not initialized."),null):(P7("getCastSelector: Cast API is not installed!"),null)},V7=function(){T7()?R7()?U7()?(N7("Requesting cast selector."),R7().requestSession()):(N7("Wait for cast API to be ready to request the session."),S7.push(g.hG("yt-remote-cast2-api-ready",V7))):P7("requestCastSelector: Cast is not initialized."):P7("requestCastSelector: Cast API is not installed!")},W7=
function(a,b){U7()?R7().setConnectedScreenStatus(a,b):P7("setConnectedScreenStatus called before ready.")},QCa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.NH||a},$Ca=function(a,b){R7().init(a,b)},RCa=function(a,b,c,d){var e=!1;
R7()||(a=new J7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.bH("yt-remote-cast-available",a);g.lG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){N7("onReceiverSelected: "+a.friendlyName);
g.bH("yt-remote-cast-receiver",a);g.lG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){N7("onReceiverResumed: "+a.friendlyName);
g.bH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){N7("onSessionChange: "+s6(a));
a||g.dH("yt-remote-cast-receiver");g.lG("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
N7("cloudview.createSingleton_: "+e);return e},R7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},SCa=function(a,b){Q7(!0);
O7(!1);$Ca(a,function(a){a?(WCa(!0),g.kG("yt-remote-cast2-api-ready")):(P7("Failed to initialize cast API."),Q7(!1),g.dH("yt-remote-cast-available"),g.dH("yt-remote-cast-receiver"),TCa());b(a)})},N7=function(a){o7("cloudview",a)},P7=function(a){o7("cloudview",a)},Q7=function(a){N7("setCastInstalled_ "+a);
g.bH("yt-remote-cast-installed",a)},U7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},WCa=function(a){N7("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},O7=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},X7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Hf=!1;this.I=this.G=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},Y7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Hf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.G=0;a.I=0;a.A=window.NaN;a.C=!1},Z7=function(a){return a.fb()?((0,g.F)()-a.D)/1E3:0},$7=function(a,b){a.F=b;
a.D=(0,g.F)()},a8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},b8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&Y7(a)},c8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.l);b.hasPrevious=a.Hf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.G;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},e8=function(a,b){g.WF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.uC;this.o=this.l=null;this.G=(0,g.z)(this.iP,this);this.D=(0,g.z)(this.Al,this);this.F=(0,g.z)(this.hP,this);this.I=(0,g.z)(this.vP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Tu,this),aDa(this))):c=3;0!=c&&(b?this.Tu(c):g.dE((0,g.z)(function(){this.Tu(c)},this),0));
var d=ZCa();d&&d8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},f8=function(a){return new X7(a.A.getPlayerContextData())},aDa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.IR,a),this))},a)},bDa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},g8=function(a,b){50>a.B.Ac()&&g.wC(a.B,b)},i8=function(a,b,c){var d=f8(a);
$7(d,c);-1E3!=d.g&&(d.g=b);h8(a,d)},j8=function(a,b,c){a.A.sendMessage(b,c)},h8=function(a,b){bDa(a);
a.A.setPlayerContextData(c8(b));aDa(a)},d8=function(a,b){a.o&&(a.o.removeUpdateListener(a.G),a.o.removeMediaListener(a.D),a.Al(null));
a.o=b;a.o&&(o7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.G),a.o.addMediaListener(a.D),a.o.media.length&&a.Al(a.o.media[0]))},cDa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=f8(a);b.contentId!=d.videoId&&o7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;$7(d,a.l.getEstimatedTime());h8(a,d)}else o7("CP","No cast media video. Ignoring state update.")},k8=function(a,b,c){return(0,g.z)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),j8(this,b,c))},a)},l8=function(a,b,c){g.WF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.G=this.K=this.L=window.NaN;this.R=[];this.A=this.D=this.o=this.Va=this.g=null;this.oa=a;this.R.push(g.FF(window,"beforeunload",(0,g.z)(this.sI,this)));this.l=[];this.Va=new X7;this.X=b.id;this.g=dDa(this,c);this.g.subscribe("handlerOpened",this.mP,this);this.g.subscribe("handlerClosed",this.jP,this);this.g.subscribe("handlerError",this.kP,this);this.g.subscribe("handlerMessage",this.lP,this);qCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Va.videoId;g.eH()&&g.bH("yt-remote-session-video-id",a)},this)},m8=function(a){o7("conn",a)},dDa=function(a,b){return new i7(l7(a.oa,"/bc"),b)},n8=function(a,b){a.P("proxyStateChange",b)},eDa=function(a){a.B=g.dE((0,g.z)(function(){m8("Connecting timeout");
this.C(1)},a),2E4)},o8=function(a){g.fE(a.B);
a.B=window.NaN},p8=function(a){g.fE(a.L);
a.L=window.NaN},fDa=function(a){q8(a);
a.K=g.dE((0,g.z)(function(){r8(this,"getNowPlaying")},a),2E4)},q8=function(a){g.fE(a.K);
a.K=window.NaN},hDa=function(a,b){b&&(o8(a),p8(a));
b==(j7(a.g)&&(0,window.isNaN)(a.B))?b&&(n8(a,1),r8(a,"getSubtitlesTrack")):b?(a.W()&&a.Va.reset(),n8(a,1),r8(a,"getNowPlaying"),gDa(a)):a.C(1)},iDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Va.videoId&&(g.Yb(b.params)?a.Va.l=null:a.Va.l=b.params,a.P("remotePlayerChange"))},jDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Va.listId=b.params.listId||a.Va.listId;b8(a.Va,c,d);a.P("remoteQueueChange")},lDa=function(a,b){b.params=b.params||{};
jDa(a,b);kDa(a,b);a.P("autoplayDismissed")},kDa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
$7(a.Va,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Va.g&&(c=-1E3);a.Va.g=c;c=Number(b.params.loadedTime);a.Va.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Va.G=(0,window.isNaN)(c)?0:c;c=a.Va;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Va;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Va.g?fDa(a):q8(a);
a.P("remotePlayerChange")},mDa=function(a,b){if(-1E3!=a.Va.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Va.g=c;c=(0,window.parseInt)(b.params.currentTime,10);$7(a.Va,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},nDa=function(a,b){var c="true"==b.params.muted;
a.Va.volume=(0,window.parseInt)(b.params.volume,10);a.Va.muted=c;a.P("remotePlayerChange")},oDa=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},pDa=function(a,b){var c="true"==b.params.hasNext;
a.Va.Hf="true"==b.params.hasPrevious;a.Va.hasNext=c;a.P("previousNextChange")},gDa=function(a){g.fE(a.I);
a.I=g.dE((0,g.z)(a.C,a,1),864E5)},r8=function(a,b,c){c?m8("Sending: action="+b+", params="+g.Bg(c)):m8("Sending: action="+b);
a.g.sendMessage(b,c)},s8=function(a){s7.call(this,"ScreenServiceProxy");
this.Xc=a;this.l=[];this.l.push(this.Xc.$_s("screenChange",(0,g.z)(this.kV,this)));this.l.push(this.Xc.$_s("onlineScreenChange",(0,g.z)(this.iR,this)))},uDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.YD("MDX_CONFIG")||b;vBa();A6();t8||(t8=new k7(b?b.loungeApiHost:void 0),DBa()&&(t8.g="/api/loungedev"));u8||(u8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",u8,void 0));qDa();var c=v8();if(!c){var d=new B7(t8);g.va("yt.mdx.remote.screenService_",d,void 0);c=v8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);VCa(a,d,function(a){a?w8()&&W7(w8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.lG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),x8("Initializing: "+g.Bg(b)),y8.push(g.hG("yt-remote-cast2-availability-change",function(){g.lG("yt-remote-receiver-availability-change")})),y8.push(g.hG("yt-remote-cast2-receiver-selected",function(){z8(null);
g.lG("yt-remote-auto-connect","cast-selector-receiver")})),y8.push(g.hG("yt-remote-cast2-receiver-resumed",function(){g.lG("yt-remote-receiver-resumed","cast-selector-receiver")})),y8.push(g.hG("yt-remote-cast2-session-change",rDa)),y8.push(g.hG("yt-remote-connection-change",function(a){a?W7(w8(),"YouTube TV"):A8()||(W7(null,null),YCa())})),a=B8(),b.isAuto&&(a.id+="#dial"),g.bG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),x8(" -- with channel params: "+
g.Bg(a)),sDa(a),c.start(),w8()||tDa())},wDa=function(){var a=vDa();
T7()&&g.cH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},vDa=function(){var a=v8().Xc.$_gos();
var b=C8();b&&D8()&&(v6(a,b)||a.push(b));return uBa(a)},E8=function(){var a=xDa();
!a&&T7()&&XCa()&&(a={key:"cast-selector-receiver",name:XCa()});return a},xDa=function(){var a=vDa(),b=C8();
b||(b=A8());return g.Ma(a,function(a){return b&&r6(b,a.key)?!0:!1})},C8=function(){var a=w8();
if(!a)return null;var b=v8().ge();return w6(b,a)},rDa=function(a){x8("remote.onCastSessionChange_: "+s6(a));
if(a){var b=C8();b&&b.id==a.id?W7(b.id,"YouTube TV"):(b&&F8(),G8(a,1))}else D8()&&F8()},F8=function(){U7()?R7().stopSession():P7("stopSession called before API ready.");
var a=D8();a&&(a.disconnect(1),H8(null))},I8=function(){var a=D8();
return!!a&&3!=a.getProxyState()},x8=function(a){o7("remote",a)},v8=function(){if(!J8){var a=g.x("yt.mdx.remote.screenService_");
J8=a?new s8(a):null}return J8},w8=function(){return g.x("yt.mdx.remote.currentScreenId_")},yDa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},zDa=function(){return g.x("yt.mdx.remote.connectData_")},z8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},D8=function(){return g.x("yt.mdx.remote.connection_")},H8=function(a){var b=D8();
z8(null);a||yDa("");g.va("yt.mdx.remote.connection_",a,void 0);u8&&((0,g.B)(u8,function(b){b(a)}),u8.length=0);
b&&!a?g.lG("yt-remote-connection-change",!1):!b&&a&&g.lG("yt-remote-connection-change",!0)},A8=function(){var a=g.eH();
if(!a)return null;var b=v8().ge();return w6(b,a)},G8=function(a,b){C8()&&C8();
yDa(a.id);var c=new l8(t8,a,B8());c.connect(b,zDa());c.subscribe("beforeDisconnect",function(a){g.lG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){D8()&&H8(null)});
H8(c)},tDa=function(){var a=A8();
a?(x8("Resume connection to: "+s6(a)),G8(a,0)):(B6(),YCa(),x8("Skipping connecting because no session screen found."))},qDa=function(){var a=B8();
if(g.Yb(a)){a=z6();var b=g.cH("yt-remote-session-name")||"",c=g.cH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},B8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},sDa=function(a){a?(g.bH("yt-remote-session-app",a.app),g.bH("yt-remote-session-name",a.name)):(g.dH("yt-remote-session-app"),g.dH("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},K8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.TF(this);g.L(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.BQ);this.o.O(b,"captionschanged",this.gP);this.o.O(b,"captionssettingschanged",this.nD);this.o.O(b,"videoplayerreset",this.wo);this.o.O(b,"mdxautoplaycancel",this.zH);this.R=this.o.O(b,"onVolumeChange",this.yB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.LB,this);c.subscribe("remotePlayerChange",this.Dl,this);c.subscribe("remoteQueueChange",this.wo,this);c.subscribe("autoplayUpNext",this.iB,
this);c.subscribe("previousNextChange",this.IB,this);c.subscribe("nowAutoplaying",this.AB,this);c.subscribe("autoplayDismissed",this.hB,this);this.suggestion=null;this.G=new g.vP(64);this.A=new g.gu(this.jD,500,this);g.L(this,this.A);this.B=new g.gu(this.kD,1E3,this);g.L(this,this.B);this.K=new J6(this.NU,0,this);g.L(this,this.K);this.C={};this.L=new g.gu(this.LD,1E3,this);g.L(this,this.L);this.I=new g.Zk(this.lN,1E3,this);g.L(this,this.I);this.N=g.y;this.nD();this.wo();this.Dl()},L8=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.G=b||0;c.g.P("progresssync",b,d)},ADa=function(a){L8(a,0);
a.A.stop();M8(a,new g.vP(64))},O8=function(a,b){if(N8(a)&&!a.D){var c=null;
b&&(c={style:a.l.oi()},g.fc(c,b));a.g.aD(a.l.getVideoData(1).videoId,c);a.C=f8(a.g).l}},P8=function(a,b){var c=a.l.Rf();
if(c){var d=c.ee();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.xj;var m=f8(c);l=l||0;var n={videoId:k,currentIndex:l};b8(m,k,l);g.t(b)&&($7(m,b),n.currentTime=b);g.t(e)&&(n.listId=e);null!=d&&(n.playerParams=d);null!=f&&(n.clickTrackingParams=f);j8(c,"setPlaylist",n);e||h8(c,m);M8(a,new g.vP(1))},BDa=function(a,b){if(b){var c=a.l.uc("captions","tracklist",{Ly:1});
c&&c.length?(a.l.Dd("captions","track",b),a.D=!1):(a.l.Fj("captions"),a.D=!0)}else a.l.Dd("captions","track",{})},N8=function(a){return f8(a.g).videoId==a.l.getVideoData(1).videoId},M8=function(a,b){a.B.stop();
var c=a.G;if(!g.DP(c,b)){var d=g.V(b,2);d!=g.V(a.G,2)&&g.VU(a.l,d);a.G=b;CDa(a.F,c,b)}},Q8=function(a){g.U.call(this,{H:"div",
M:"ytp-remote",J:[{H:"div",M:"ytp-remote-display-status",J:[{H:"div",M:"ytp-remote-display-status-icon",J:[g.Yoa()]},{H:"div",M:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.o=new g.GV(this,250);g.L(this,this.o);this.A=a;this.O(a,"presentingplayerstatechange",this.B);DDa(this,g.SU(a))},DDa=function(a,b){if(3==a.A.Qa()){var c={RECEIVER_NAME:a.A.uc("remote","currentReceiver").name};
c=g.V(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.fb()||g.V(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},R8=function(a,b){g.PZ.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.o=a;this.G={};this.O(a,"onMdxReceiversChange",this.K);this.O(a,"presentingplayerstatechange",this.K);this.K()},S8=function(a){g.pV.call(this,a);
g.gH({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:u6(),name:g.T("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.vP(64);this.G=0;if(!g.LM(g.W(this.g))){a=
this.g;var b=g.$I(a);b&&(b=b.ao())&&(b=new R8(a,b),g.L(this,b));b=new Q8(a);g.L(this,b);g.jV(a,b.element,4)}},CDa=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.JP(c,b))},T8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)F8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1),e=d.videoId;if(c||e){var f=a.g.Rf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.gc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.xj,index:Math.max(a.g.Oz(),0),currentTime:0==f?void 0:f}}else c=null;x8("Connecting to: "+g.Bg(b));"cast-selector-receiver"==b.key?(z8(c||null),U7()?R7().setLaunchParams(c||null):P7("setLaunchParams called before ready.")):
!c&&I8()&&w8()==b.key?g.lG("yt-remote-connection-change",!0):(F8(),z8(c||null),c=v8().ge(),(c=w6(c,b.key))&&G8(c,1))}},SBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},T6={"'":"\\'"},EDa={},qBa={DW:"atp",X0:"ska",o0:"que",A_:"mus",T0:"sus",LY:"dsp"};
p6.prototype.Vm=function(){var a=new p6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var C6,y6="",G6=D6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",KBa=D6("loadCastFramework")||D6("loadCastApplicationFramework"),UCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(J6,g.K);g.h=J6.prototype;g.h.nI=function(a){this.A=arguments;this.g=!1;this.va?this.o=(0,g.F)()+this.Yc:this.va=g.vg(this.B,this.Yc)};
g.h.stop=function(){this.va&&(g.wg(this.va),this.va=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();J6.Z.V.call(this)};
g.h.oI=function(){this.o?(this.va=g.vg(this.B,this.o-(0,g.F)()),this.o=null):(this.va=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};K6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
K6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=L6.prototype;g.h.Wh=null;g.h.qf=!1;g.h.lk=null;g.h.Nu=null;g.h.Tj=null;g.h.oj=null;g.h.Ug=null;g.h.sh=null;g.h.yi=null;g.h.Nc=null;g.h.Rl=0;g.h.rf=null;g.h.vp=null;g.h.Vg=null;g.h.Qk=-1;g.h.GC=!0;g.h.Ih=!1;g.h.gr=0;g.h.Go=null;var QBa={},O6={};g.h=L6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.CT=function(a){a=a.target;var b=this.Go;b&&3==g.ux(a)?b.mj():this.UD(a)};
g.h.UD=function(a){try{if(a==this.Nc)a:{var b=g.ux(this.Nc),c=this.Nc.l,d=this.Nc.getStatus();if(g.yd&&!g.sc(10)||g.Ad&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.gf&&!g.yx(this.Nc))break a;this.Ih||4!=b||7==c||(8==c||0>=d?this.g.jf(3):this.g.jf(2));V6(this);var e=this.Nc.getStatus();this.Qk=e;var f=g.yx(this.Nc);(this.qf=200==e)?(4==b&&R6(this),this.C?(RBa(this,b,f),g.gf&&this.qf&&3==b&&(this.A.T(this.l,"tick",this.yT),this.l.start())):Q6(this,f),this.qf&&!this.Ih&&(4==b?this.g.uo(this):
(this.qf=!1,N6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Vg=3,P6(13)):(this.Vg=0,P6(14)),R6(this),S6(this))}}catch(k){this.Nc&&g.yx(this.Nc)}finally{}};
g.h.yT=function(){var a=g.ux(this.Nc),b=g.yx(this.Nc);this.Rl<b.length&&(V6(this),RBa(this,a,b),this.qf&&4!=a&&N6(this))};
g.h.IS=function(a){U6((0,g.z)(this.HS,this,a),0)};
g.h.HS=function(a){this.Ih||(V6(this),Q6(this,a),N6(this))};
g.h.TB=function(a){U6((0,g.z)(this.GS,this,a),0)};
g.h.GS=function(a){this.Ih||(R6(this),this.qf=a,this.g.uo(this),this.g.jf(4))};
g.h.cancel=function(){this.Ih=!0;R6(this)};
g.h.ZS=function(){this.lk=null;var a=(0,g.F)();0<=a-this.Nu?(2!=this.oj&&this.g.jf(3),R6(this),this.Vg=2,P6(18),S6(this)):UBa(this,this.Nu-a)};g.h=XBa.prototype;g.h.ar=null;g.h.ne=null;g.h.Ho=!1;g.h.Xx=null;g.h.ln=null;g.h.dr=null;g.h.fr=null;g.h.Ge=null;g.h.og=-1;g.h.Pk=null;g.h.rk=null;g.h.connect=function(a){this.fr=a;a=X6(this.g,null,this.fr);P6(3);this.Xx=(0,g.F)();var b=this.g.F;null!=b?(this.Pk=b[0],(this.rk=b[1])?(this.Ge=1,YBa(this)):(this.Ge=2,Z6(this))):(o6(a,"MODE","init"),this.ne=new L6(this,void 0,void 0,void 0),this.ne.Wh=this.ar,M6(this.ne,a,!1,null,!0),this.Ge=0)};
g.h.AH=function(a){if(a)this.Ge=2,Z6(this);else{P6(4);var b=this.g;b.Ef=b.Lg.og;f7(b,9)}a&&this.jf(2)};
g.h.Aq=function(a){return this.g.Aq(a)};
g.h.abort=function(){this.ne&&(this.ne.cancel(),this.ne=null);this.og=-1};
g.h.Wx=function(){return!1};
g.h.MB=function(a,b){this.og=a.Qk;if(0==this.Ge)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Ef=this.og;f7(c,2);return}this.Pk=c[0];this.rk=c[1]}else c=this.g,c.Ef=this.og,f7(c,2);else if(2==this.Ge)if(this.Ho)P6(7),this.dr=(0,g.F)();else if("11111"==b){if(P6(6),this.Ho=!0,this.ln=(0,g.F)(),c=this.ln-this.Xx,!g.yd||g.sc(10)||500>c)this.og=200,this.ne.cancel(),P6(12),Y6(this.g,this,!0)}else P6(8),this.ln=this.dr=(0,g.F)(),this.Ho=!1};
g.h.uo=function(){this.og=this.ne.Qk;if(this.ne.qf)0==this.Ge?this.rk?(this.Ge=1,YBa(this)):(this.Ge=2,Z6(this)):2==this.Ge&&((!g.yd||g.sc(10)?!this.Ho:200>this.dr-this.ln)?(P6(11),Y6(this.g,this,!1)):(P6(12),Y6(this.g,this,!0)));else{0==this.Ge?P6(9):2==this.Ge&&P6(10);var a=this.g;a.Ef=this.og;f7(a,2)}};
g.h.Ll=function(){return this.g.Ll()};
g.h.isActive=function(){return this.g.isActive()};
g.h.jf=function(a){this.g.jf(a)};g.h=$6.prototype;g.h.Ck=null;g.h.Od=null;g.h.qc=null;g.h.Zq=null;g.h.qn=null;g.h.ow=null;g.h.Cn=null;g.h.xl=0;g.h.yO=0;g.h.md=null;g.h.Ng=null;g.h.hg=null;g.h.Mh=null;g.h.Lg=null;g.h.tp=null;g.h.Bj=-1;g.h.Zy=-1;g.h.Ef=-1;g.h.cj=0;g.h.Qi=0;g.h.Kh=8;var g7=new g.Gf;g.A($Ba,g.ef);g.A(aCa,g.ef);g.A(bCa,g.ef);g.h=$6.prototype;g.h.connect=function(a,b,c,d,e){P6(0);this.Zq=b;this.Ck=c||{};d&&g.t(e)&&(this.Ck.OSID=d,this.Ck.OAID=e);this.C?(U6((0,g.z)(this.Lw,this,a),100),fCa(this)):this.Lw(a)};
g.h.Lw=function(a){this.Lg=new XBa(this);this.Lg.ar=null;this.Lg.l=this.B;this.Lg.connect(a)};
g.h.Wx=function(){return 0==this.g};
g.h.RB=function(a){this.Ng=null;iCa(this,a)};
g.h.QB=function(){this.hg=null;this.qc=new L6(this,this.o,"rpc",this.D);this.qc.Wh=null;this.qc.gr=0;var a=this.ow.clone();g.Om(a,"RID","rpc");g.Om(a,"SID",this.o);g.Om(a,"CI",this.tp?"0":"1");g.Om(a,"AID",this.Bj);a7(this,a);if(!g.yd||g.sc(10))g.Om(a,"TYPE","xmlhttp"),M6(this.qc,a,!0,this.Cn,!1);else{g.Om(a,"TYPE","html");var b=this.qc,c=!!this.Cn;b.oj=3;b.Ug=n6(a.clone());TBa(b,c)}};
g.h.MB=function(a,b){if(0!=this.g&&(this.qc==a||this.Od==a))if(this.Ef=a.Qk,this.Od==a&&3==this.g)if(7<this.Kh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.hg){if(this.qc)if(this.qc.Tj+3E3<this.Od.Tj)c7(this),this.qc.cancel(),this.qc=null;else break a;e7(this);P6(19)}}else this.Zy=c[1],0<this.Zy-this.Bj&&37500>c[2]&&this.tp&&0==this.Qi&&!this.Mh&&(this.Mh=U6((0,g.z)(this.bP,this),6E3));else f7(this,11)}else b!=EDa.GX.g&&f7(this,11);else if(this.qc==a&&
c7(this),!g.C(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.Bj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Cn=e[2],e=e[3],null!=e?this.Kh=e:this.Kh=6,this.g=3,this.md&&this.md.Bw(),this.ow=X6(this,this.Ll()?this.Cn:null,this.Zq),jCa(this)):"stop"==e[0]&&f7(this,7):3==this.g&&("stop"==e[0]?f7(this,7):"noop"!=e[0]&&this.md&&this.md.Aw(e),this.Qi=0)}}};
g.h.bP=function(){null!=this.Mh&&(this.Mh=null,this.qc.cancel(),this.qc=null,e7(this),P6(20))};
g.h.uo=function(a){if(this.qc==a){c7(this);this.qc=null;var b=2}else if(this.Od==a)this.Od=null,b=1;else return;this.Ef=a.Qk;if(0!=this.g)if(a.qf)1==b?(b=(0,g.F)()-a.Tj,g7.dispatchEvent(new aCa(g7,a.yi?a.yi.length:0,b,this.cj)),b7(this),this.A.length=0):jCa(this);else{var c=a.Vg,d;if(!(d=3==c||7==c||0==c&&0<this.Ef)){if(d=1==b)this.Od||this.Ng||1==this.g||2<=this.cj?d=!1:(this.Ng=U6((0,g.z)(this.RB,this,a),kCa(this,this.cj)),this.cj++,d=!0);d=!(d||2==b&&e7(this))}if(d)switch(c){case 1:f7(this,5);
break;case 4:f7(this,10);break;case 3:f7(this,6);break;case 7:f7(this,12);break;default:f7(this,2)}}};
g.h.VH=function(a){if(!g.Qa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.xU=function(a){a?P6(2):(P6(1),lCa(this,8))};
g.h.Aq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.mx;a.F=!1;return a};
g.h.isActive=function(){return!!this.md&&this.md.isActive(this)};
g.h.jf=function(a){g7.dispatchEvent(new bCa(g7,a))};
g.h.Ll=function(){return!(!g.yd||g.sc(10))};
g.h=mCa.prototype;g.h.Bw=function(){};
g.h.Aw=function(){};
g.h.zw=function(){};
g.h.mq=function(){};
g.h.Ex=function(){return{}};
g.h.isActive=function(){return!0};g.A(h7,g.K);g.h=h7.prototype;g.h.zS=function(){this.Yc=Math.min(3E5,2*this.Yc);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.Yc+15E3*Math.random();g.hu(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Yc=5E3};g.A(i7,mCa);g.h=i7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Fd=function(a){return this.o.Fd(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.cf(this.o),pCa(this),g.cf(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.G="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new $6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.g;e&&(e.md=null);d.md=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Bj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):j7(this)&&gCa(this.g,c)};
g.h.Bw=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)gCa(this.g,a[b])}this.P("handlerOpened")};
g.h.zw=function(a){var b=2==a&&401==this.g.Ef;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.mq=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Ex=function(){var a={v:2};this.G&&(a.gsessionid=this.G);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.fc(a,this.B);return a};
g.h.Aw=function(a){"S"==a[0]?this.G=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),eCa(this.g)):this.P("handlerMessage",new nCa(a[0],a[1]))};
g.h.gV=function(){this.l.isActive();var a=this.g,b=0;a.qc&&b++;a.Od&&b++;0!=b||this.connect(this.B,this.A)};k7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
k7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
k7.prototype.B=function(a){a(Error("request timed out"))};var xCa=(0,g.F)(),n7=null,q7=Array(50),p7=-1,r7=!1;g.A(s7,g.WF);s7.prototype.ge=function(){return this.g};
s7.prototype.contains=function(a){return!!v6(this.g,a)};
s7.prototype.get=function(a){return a?w6(this.g,a):null};
s7.prototype.info=function(a){o7(this.D,a)};g.A(t7,g.WF);var FDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=t7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.va)&&this.ZD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.va)||(g.fE(this.va),this.va=window.NaN)};
g.h.V=function(){this.stop();t7.Z.V.call(this)};
g.h.ZD=function(){this.va=window.NaN;this.g=g.BE(l7(this.C,"/pairing/get_screen"),{method:"POST",Jb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.iV,this),onError:(0,g.z)(this.hV,this),rd:(0,g.z)(this.jV,this)})};
g.h.iV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new q6(c))};
g.h.hV=function(a){this.g=null;a.status&&404==a.status?this.l>=FDa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=FDa[this.l],this.va=g.dE((0,g.z)(this.ZD,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.jV=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.A(v7,s7);g.h=v7.prototype;g.h.start=function(){u7(this)&&this.P("screenChange");!g.cH("yt-remote-lounge-token-expiration")&&BCa(this);g.fE(this.l);this.l=g.dE((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){u7(this);yCa(this,a);w7(this,!1);this.P("screenChange");b(a);a.token||BCa(this)};
g.h.remove=function(a,b){var c=u7(this);ACa(this,a)&&(w7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.mp=function(a,b,c,d){var e=u7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,w7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.V=function(){g.fE(this.l);v7.Z.V.call(this)};
g.h.BI=function(a){u7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}w7(this,!b);b&&o7(this.D,"Missed "+b+" lounge tokens.")};
g.h.AI=function(a){o7(this.D,"Requesting lounge tokens failed: "+a)};g.A(y7,g.WF);g.h=y7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.cH("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?A7(this):(this.A=(0,g.F)()+3E5,g.bH("yt-remote-fast-check-period",this.A),this.cu())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){x7("Updating availability on schedule.");var a=this.C(),b=g.Lb(this.g,function(b,d){return b&&!!w6(a,d)},this);
z7(this,b)};
g.h.V=function(){g.fE(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);y7.Z.V.call(this)};
g.h.cu=function(){g.fE(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=ECa(this);if(g.Pb(a)){var b=l7(this.B,"/pairing/get_screen_availability");this.l=m7(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.hS,this,a),(0,g.z)(this.gS,this))}else z7(this,{}),A7(this)};
g.h.hS=function(a,b){this.l=null;var c=g.Sb(ECa(this));if(g.jb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;z7(this,d);A7(this)}else this.ac("Changing Screen set during request."),this.cu()};
g.h.gS=function(a){this.ac("Screen availability failed: "+a);this.l=null;A7(this)};
g.h.ac=function(a){o7("OnlineScreenService",a)};g.A(B7,s7);g.h=B7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.mp=function(a,b,c,d){this.o.contains(a)?this.o.mp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,o7(this.D,a),d(Error(a)))};
g.h.ge=function(a){return a?this.g:g.Xa(this.g,(0,g.Ld)(this.A,function(a){return!this.contains(a)},this))};
g.h.aE=function(){return(0,g.Ld)(this.ge(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.bE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new t7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.cf(f);d(C7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.cf(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.lV=function(a,b,c,d){g.BE(l7(this.C,"/pairing/get_screen"),{method:"POST",Jb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new q6(d.screen||{});if(!e.name||ICa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);ICa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(C7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
rd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.cf(this.o);g.cf(this.l);B7.Z.V.call(this)};
g.h.RI=function(){JCa(this);this.P("screenChange");this.l.update()};
B7.prototype.dispose=B7.prototype.dispose;g.A(E7,g.WF);g.h=E7.prototype;g.h.vo=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.ke=function(a){this.ha()||(a&&F7(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){o7(this.L,a)};
g.h.dE=function(){return null};
g.h.ju=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){F7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.ju("");E7.Z.V.call(this)};g.A(G7,E7);g.h=G7.prototype;g.h.iu=function(a){if(this.g){if(this.g==a)return;F7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);LCa(this)};
g.h.Cj=function(a){this.info("launchWithParams no-op for Cast: "+g.Bg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.ke()},this),(0,g.z)(function(){this.ke(Error("Failed to stop receiver app."))},this)):this.ke(Error("Stopping cast device witout session."))};
g.h.ju=g.y;g.h.V=function(){this.info("disposeInternal");g.fE(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;G7.Z.V.call(this)};
g.h.lT=function(a,b){if(!this.ha())if(b){var c=g.gx(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Bg(c));switch(d){case "mdxSessionStatus":KCa(this,c.screenId);break;default:F7(this,"Unknown youtube message: "+d)}}else F7(this,"Unable to parse message.")}else F7(this,"No data in message.")};
g.h.Px=function(a,b,c,d){HCa(this.G,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(F7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.dE((0,g.z)(this.Px,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.dE=function(){return this.g};
g.h.mV=function(a){this.ha()||a||(F7(this,"Cast session died."),this.ke())};g.A(H7,E7);g.h=H7.prototype;g.h.iu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Cj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.fE(this.C);this.A?this.A.stop((0,g.z)(this.ke,this,null),(0,g.z)(this.ke,this,"Failed to stop DIAL device.")):this.ke()};
g.h.V=function(){this.g();this.g=g.y;g.fE(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;H7.Z.V.call(this)};
g.h.pV=function(a){this.ha()||a||(F7(this,"DIAL session died."),this.g(),this.g=g.y,this.ke())};
g.h.Rr=function(a){this.I=u6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,NCa(this));a(b);MCa(this)}else this.D=(0,g.z)(function(){g.fE(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,NCa(this));a(b);MCa(this)},this),this.C=g.dE((0,g.z)(function(){this.D()},this),100)};
g.h.gK=function(a,b,c){HCa(this.G,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.vo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Rr(b,c)},this),(0,g.z)(function(a){F7(this,"Failed to get DIAL screen: "+a);
this.Rr(b,c)},this))};g.A(I7,E7);I7.prototype.stop=function(){this.ke()};
I7.prototype.iu=g.y;I7.prototype.Cj=function(){g.fE(this.g);this.g=window.NaN;var a=w6(this.G.ge(),this.l.label);a?this.vo(a):this.ke(Error("No such screen"))};
I7.prototype.V=function(){g.fE(this.g);this.g=window.NaN;I7.Z.V.call(this)};g.A(J7,g.WF);g.h=J7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.NB,this),(0,g.z)(this.RR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.MP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),uCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.cE,this)),this.o=PCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.Bg(a))},this)),this.P("yt-remote-cast2-availability-change",L7(this)),b(!0))},this),(0,g.z)(function(a){this.ac("Failed to initialize API: "+g.Bg(a));
b(!1)},this))};
g.h.hU=function(a,b){K7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)K7("Unsetting old screen status: "+this.g.l.friendlyName),M7(this,null)}if(a&&b){if(!this.g){c=w6(this.l.ge(),a);if(!c){K7("setConnectedScreenStatus: Unknown screen.");return}var d=OCa(this,c);d||(K7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.Bg(a))},this)));
K7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);M7(this,new I7(this.l,d),!0)}this.g.ju(b)}else K7("setConnectedScreenStatus: no screen.")};
g.h.iU=function(a){this.ha()?this.ac("Setting connection data on disposed cast v2"):this.g?this.g.Cj(a):this.ac("Setting connection data without a session")};
g.h.oV=function(){this.ha()?this.ac("Stopping session on disposed cast v2"):this.g?(this.g.stop(),M7(this,null)):K7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.NB,this),(0,g.z)(this.mS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.cE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Va(g.x("yt.mdx.remote.debug.handlers_")||[],rCa);g.cf(this.g);J7.Z.V.call(this)};
g.h.ac=function(a){o7("Controller",a)};
g.h.OB=function(a,b){this.g==a&&(b||M7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.NR=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),K7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)K7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{K7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:M7(this,
new I7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:M7(this,new H7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:M7(this,new G7(this.l,a));break;default:this.ac("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.ac("Stopping receiver w/o session: "+a.friendlyName)}else this.ac("onReceiverAction_ called without receiver.")};
g.h.MP=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.ac("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.ac("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return K7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.ac('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);M7(this,new H7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.gK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Rr,b))};
g.h.NB=function(a){if(!this.ha()){K7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)K7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),M7(this,new G7(this.l,b),!0);else{this.ac("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=w6(this.l.ge(),c.label);
d&&r6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(K7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.cf(this.g),this.g=new G7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.OB,this,this.g)),this.g.Cj(null));this.g.iu(a)}}};
g.h.nV=function(){return this.g?this.g.dE():null};
g.h.mS=function(a){this.ha()||(this.ac("Failed to estabilish a session: "+g.Bg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&M7(this,null))};
g.h.RR=function(a){K7("Receiver availability updated: "+a);if(!this.ha()){var b=L7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;L7(this)!=b&&this.P("yt-remote-cast2-availability-change",L7(this))}};
g.h.cE=function(){this.ha()||(this.o=PCa(this),K7("Updating custom receivers: "+g.Bg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.ac("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",L7(this)))};
J7.prototype.setLaunchParams=J7.prototype.iU;J7.prototype.setConnectedScreenStatus=J7.prototype.hU;J7.prototype.stopSession=J7.prototype.oV;J7.prototype.getCastSession=J7.prototype.nV;J7.prototype.requestSession=J7.prototype.requestSession;J7.prototype.init=J7.prototype.init;J7.prototype.dispose=J7.prototype.dispose;var S7=[];g.h=X7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";Y7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Hf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.G=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.fb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.G+Z7(this):this.G};
g.h.clone=function(){return new X7(c8(this))};g.A(e8,g.WF);g.h=e8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,k8(this,"play")):j8(this,"play"),i8(this,1,a8(f8(this))),this.P("remotePlayerChange")):g8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,k8(this,"pause")):j8(this,"pause"),i8(this,2,a8(f8(this))),this.P("remotePlayerChange")):g8(this,this.pause)};
g.h.YD=function(a){if(1==this.g){if(this.l){var b=f8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.fb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,k8(this,"seekTo",{newTime:a}))}else j8(this,"seekTo",{newTime:a});i8(this,3,a);this.P("remotePlayerChange")}else g8(this,g.Ea(this.YD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,k8(this,"stopVideo")):j8(this,"stopVideo");var a=f8(this);a.index=-1;a.videoId="";Y7(a);h8(this,a);this.P("remotePlayerChange")}else g8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=f8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){o7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){o7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);j8(this,"setVolume",e)}c.muted=b;c.volume=a;h8(this,c)}else g8(this,g.Ea(this.setVolume,a,b))};
g.h.aD=function(a,b){if(1==this.g){var c=f8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Bg(b.style),g.fc(d,c.l));j8(this,"setSubtitlesTrack",d);h8(this,c)}else g8(this,g.Ea(this.aD,a,b))};
g.h.Su=function(a,b){if(1==this.g){j8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Mb.id});var c=f8(this);c.audioTrackId=b.Mb.id;h8(this,c)}else g8(this,g.Ea(this.Su,a,b))};
g.h.XD=function(a,b){if(1==this.g){if(a&&b){var c=f8(this);b8(c,a,b);h8(this,c)}j8(this,"previous")}else g8(this,g.Ea(this.XD,a,b))};
g.h.WD=function(a,b){if(1==this.g){if(a&&b){var c=f8(this);b8(c,a,b);h8(this,c)}j8(this,"next")}else g8(this,g.Ea(this.WD,a,b))};
g.h.fx=function(){1==this.g?j8(this,"dismissAutoplay"):g8(this,this.fx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}e8.Z.dispose.call(this)};
g.h.V=function(){bDa(this);this.A=null;this.B.clear();d8(this,null);e8.Z.V.call(this)};
g.h.Tu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.xC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.IR=function(a,b){this.P(a,b)};
g.h.iP=function(a){if(!a)this.Al(null),d8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=f8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)o7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,h8(this,b)}};
g.h.Al=function(a){o7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),cDa(this),this.P("remotePlayerChange")};
g.h.hP=function(a){a?(cDa(this),this.P("remotePlayerChange")):this.Al(null)};
g.h.vP=function(){var a=ZCa();a&&d8(this,a)};
g.h.ac=function(a){o7("CP",a)};g.A(l8,g.WF);g.h=l8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Va.listId=c);this.Va.videoId=d;this.Va.index=k||0;this.Va.state=3;$7(this.Va,m);this.A="UNSUPPORTED";m8("Connecting with setPlaylist and params: "+g.Bg(l));this.g.connect({method:"setPlaylist",params:g.Bg(l)},a,yBa())}else m8("Connecting without params"),
this.g.connect({},a,yBa());eDa(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),n8(this,3));l8.Z.dispose.call(this)};
g.h.V=function(){o8(this);q8(this);p8(this);g.fE(this.G);this.G=window.NaN;g.fE(this.I);this.I=window.NaN;this.o=null;g.GF(this.R);this.R.length=0;this.g.dispose();l8.Z.V.call(this);this.A=this.D=this.l=this.Va=this.g=null};
g.h.sI=function(){this.C(2)};
g.h.mP=function(){m8("Channel opened");this.N&&(this.N=!1,p8(this),this.L=g.dE((0,g.z)(function(){m8("Timing out waiting for a screen.");this.C(1)},this),15E3));
CBa(oCa(this.g),this.X)};
g.h.jP=function(){m8("Channel closed");(0,window.isNaN)(this.B)?B6(!0):B6();this.dispose()};
g.h.kP=function(a){B6();(0,window.isNaN)(this.F())?(m8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,m8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),n8(this,2))};
g.h.lP=function(a){a.params?m8("Received: action="+a.action+", params="+g.Bg(a.params)):m8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.gx(a.params.devices);this.l=(0,g.G)(a,function(a){return new p6(a)});
a=!!g.Ma(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
hDa(this,a);break;case "loungeScreenDisconnected":g.Wa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
hDa(this,!1);break;case "remoteConnected":var b=new p6(g.gx(a.params.device));g.Ma(this.l,function(a){return b?a.id==b.id:!1})||g.Ta(this.l,b);
break;case "remoteDisconnected":b=new p6(g.gx(a.params.device));g.Wa(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":jDa(this,a);break;case "nowPlaying":lDa(this,a);break;case "onStateChange":kDa(this,a);break;case "onAdStateChange":mDa(this,a);break;case "onVolumeChanged":nDa(this,a);break;case "onSubtitlesTrackChanged":iDa(this,a);break;case "nowAutoplaying":oDa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":pDa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:m8("Unrecognized action: "+a.action)}};
g.h.PT=function(){if(this.o){var a=this.o;this.o=null;this.Va.videoId!=a&&r8(this,"getNowPlaying")}};
l8.prototype.subscribe=l8.prototype.subscribe;l8.prototype.unsubscribeByKey=l8.prototype.Fd;l8.prototype.ea=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?j7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
l8.prototype.getProxyState=l8.prototype.ea;l8.prototype.C=function(a){m8("Disconnecting with "+a);o8(this);this.P("beforeDisconnect",a);1==a&&B6();pCa(this.g,a);this.dispose()};
l8.prototype.disconnect=l8.prototype.C;l8.prototype.da=function(){var a=this.Va;this.o&&(a=this.Va.clone(),b8(a,this.o,a.index));return c8(a)};
l8.prototype.getPlayerContextData=l8.prototype.da;
l8.prototype.la=function(a){var b=new X7(a);b.videoId&&b.videoId!=this.Va.videoId&&(this.o=b.videoId,g.fE(this.G),this.G=g.dE((0,g.z)(this.PT,this),5E3));var c=[];this.Va.listId==b.listId&&this.Va.videoId==b.videoId&&this.Va.index==b.index||c.push("remoteQueueChange");this.Va.g==b.g&&this.Va.volume==b.volume&&this.Va.muted==b.muted&&a8(this.Va)==a8(b)&&g.Bg(this.Va.l)==g.Bg(b.l)||c.push("remotePlayerChange");this.Va.reset(a);(0,g.B)(c,function(a){this.P(a)},this)};
l8.prototype.setPlayerContextData=l8.prototype.la;l8.prototype.W=function(){var a=this.g.C.id,b=g.Ma(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
l8.prototype.getOtherConnectedRemoteId=l8.prototype.W;l8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
l8.prototype.getReconnectTimeout=l8.prototype.F;l8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
l8.prototype.getAutoplayMode=l8.prototype.Y;l8.prototype.aa=function(){return this.D||""};
l8.prototype.getAutoplayVideoId=l8.prototype.aa;l8.prototype.pa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.iu(a.g);a.start()}};
l8.prototype.reconnect=l8.prototype.pa;l8.prototype.ga=function(a,b){r8(this,a,b);gDa(this)};
l8.prototype.sendMessage=l8.prototype.ga;g.A(s8,s7);g.h=s8.prototype;g.h.ge=function(a){return this.Xc.$_gs(a)};
g.h.contains=function(a){return!!this.Xc.$_c(a)};
g.h.get=function(a){return this.Xc.$_g(a)};
g.h.start=function(){this.Xc.$_st()};
g.h.add=function(a,b,c){this.Xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Xc.$_r(a,b,c)};
g.h.mp=function(a,b,c,d){this.Xc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.Xc.$_ubk(this.l[a]);this.l.length=0;this.Xc=null;s8.Z.V.call(this)};
g.h.kV=function(){this.P("screenChange")};
g.h.iR=function(){this.P("onlineScreenChange")};
B7.prototype.$_st=B7.prototype.start;B7.prototype.$_gspc=B7.prototype.lV;B7.prototype.$_gsppc=B7.prototype.bE;B7.prototype.$_c=B7.prototype.contains;B7.prototype.$_g=B7.prototype.get;B7.prototype.$_a=B7.prototype.add;B7.prototype.$_un=B7.prototype.mp;B7.prototype.$_r=B7.prototype.remove;B7.prototype.$_gs=B7.prototype.ge;B7.prototype.$_gos=B7.prototype.aE;B7.prototype.$_s=B7.prototype.subscribe;B7.prototype.$_ubk=B7.prototype.Fd;var t8=null,u8=null,J8=null,y8=[];g.p(K8,g.K);g.h=K8.prototype;
g.h.V=function(){g.K.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.LB,this);this.g.unsubscribe("remotePlayerChange",this.Dl,this);this.g.unsubscribe("remoteQueueChange",this.wo,this);this.g.unsubscribe("autoplayUpNext",this.iB,this);this.g.unsubscribe("previousNextChange",this.IB,this);this.g.unsubscribe("nowAutoplaying",this.AB,this);this.g.unsubscribe("autoplayDismissed",this.hB,this);this.g=this.F=null};
g.h.kA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(N8(this)){if(!f8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":f8(this.g).fb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.mj(c[0],c[1]);break;case "control_subtitles_set_track":O8(this,c[0]);break;case "control_set_audio_track":c=c[0],N8(this)&&this.g.Su(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();P8(this,0==c?void 0:c);break;case "control_seek":P8(this,c[0]);break;case "control_subtitles_set_track":O8(this,c[0]);break;case "control_set_audio_track":c=c[0],N8(this)&&this.g.Su(this.l.getVideoData(1).videoId,c)}};
g.h.gP=function(a){this.K.nI(a)};
g.h.NU=function(a){this.kA("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.nD=function(){var a=this.l.uc("captions","track");g.Yb(a)||O8(this,a)};
g.h.yB=function(a){if(N8(this)){this.g.unsubscribe("remotePlayerChange",this.Dl,this);var b=Math.round(a.volume);a=!!a.muted;var c=f8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.Dl,this)}};
g.h.BQ=function(){g.Yb(this.C)||BDa(this,this.C);this.D=!1};
g.h.LB=function(a,b){this.B.stop();2==b&&this.kD()};
g.h.Dl=function(){if(N8(this)){this.A.stop();var a=f8(this.g);switch(a.g){case 1081:case 1:M8(this,new g.vP(8));this.jD();break;case 1085:case 3:M8(this,new g.vP(9));break;case 1083:case 0:M8(this,new g.vP(2));this.I.stop();L8(this,this.l.getVideoData().lengthSeconds);break;case 1084:M8(this,new g.vP(4));break;case 2:M8(this,new g.vP(4));L8(this,a8(a));break;case -1:M8(this,new g.vP(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},M8(this,new g.vP(128,a))}a=
f8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,BDa(this,a));a=f8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.L.isActive()||this.LD()}else ADa(this)};
g.h.IB=function(){this.l.P("mdxpreviousnextchange")};
g.h.wo=function(){N8(this)||ADa(this)};
g.h.zH=function(){this.g.fx()};
g.h.iB=function(a){a&&(a=g.BE("/watch_queue_ajax",{method:"GET",Tc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.LS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.LS=function(a,b){var c=new g.hO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.AB=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.hB=function(){this.l.P("mdxautoplaycanceled")};
g.h.lN=function(a,b){-1==f8(this.g).g?P8(this,a):b&&this.g.YD(a)};
g.h.LD=function(){if(N8(this)){var a=f8(this.g);this.o.Aa(this.R);a.muted?this.l.mute():this.l.Sf();this.l.setVolume(a.volume);this.R=this.o.O(this.l,"onVolumeChange",this.yB)}};
g.h.jD=function(){this.A.stop();if(!this.g.ha()){var a=f8(this.g);a.fb()&&M8(this,new g.vP(8));L8(this,a8(a));this.A.start()}};
g.h.kD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(Q8,g.U);Q8.prototype.B=function(a){DDa(this,a.state)};g.p(R8,g.PZ);R8.prototype.K=function(){var a=this.o.uc("remote","receivers");a&&1<a.length&&!this.o.uc("remote","quickCast")?(this.G=g.lb(a,this.C,this),g.QZ(this,(0,g.G)(a,this.C)),a=this.o.uc("remote","currentReceiver"),this.hf(this.C(a)),this.enable(!0)):this.enable(!1)};
R8.prototype.C=function(a){return a.key};
R8.prototype.gf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
R8.prototype.pd=function(a){g.PZ.prototype.pd.call(this,a);this.o.Dd("remote","currentReceiver",this.G[a]);this.B.Nb()};g.p(S8,g.pV);g.h=S8.prototype;g.h.create=function(){uDa(g.yM(g.W(this.g)));this.C.push(g.hG("yt-remote-before-disconnect",this.cP,this));this.C.push(g.hG("yt-remote-connection-change",this.SR,this));this.C.push(g.hG("yt-remote-receiver-availability-change",this.JB,this));this.C.push(g.hG("yt-remote-auto-connect",this.QR,this));this.C.push(g.hG("yt-remote-receiver-resumed",this.PR,this));this.JB()};
g.h.load=function(){this.g.Ps();g.pV.prototype.load.call(this);this.B=new K8(this,this.g,this.l);var a=(a=zDa())?a.currentTime:0;var b=I8()?new e8(D8(),void 0):null;0==a&&b&&(a=a8(f8(b)));0!=a&&(this.G=a||0,this.g.P("progresssync",a,void 0));CDa(this,this.D,this.D);g.a0(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.df(this.B,this.l);this.l=this.B=null;g.pV.prototype.unload.call(this);g.a0(this.g.app,5)};
g.h.V=function(){g.iG(this.C);g.pV.prototype.V.call(this)};
g.h.sl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.kA.apply(this.B,[a].concat(g.oa(c)))};
g.h.jI=function(){return this.loaded?this.B.suggestion:null};
g.h.Hf=function(){return this.l?f8(this.l).Hf:!1};
g.h.hasNext=function(){return this.l?f8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.G};
g.h.ZM=function(){var a=f8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.Zc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+Z7(a):a.A,isPeggedToLive:1>=(a.C?a.o+Z7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+Z7(a):a.o,seekableStart:0<a.B?a.B+Z7(a):a.B}};
g.h.aN=function(){this.l&&this.l.WD()};
g.h.bN=function(){this.l&&this.l.XD()};
g.h.cP=function(a){1==a&&(this.I=this.l?f8(this.l):null)};
g.h.SR=function(){var a=I8()?new e8(D8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.cf(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.Mz(a.videoId,a8(a)));this.g.P("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.JB=function(){this.F=[this.o].concat(wDa());var a=E8()||this.o;T8(this,a);this.g.ra("onMdxReceiversChange")};
g.h.QR=function(){var a=E8();T8(this,a)};
g.h.PR=function(){this.A=E8()};
g.h.YM=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?V7():T8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&V7(),!0):!1}};
g.h.cN=function(){j8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Kc=function(){return!1};g.gY.remote=S8;})(_yt_player);
